# Generated by health_care 5.1.3 on 2024-12-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallen',
            name='last_fallen_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_field',
            field=models.TimeField(),
        ),
    ]
