# Generated by health_care 5.1.3 on 2024-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_app', '0002_alter_fallen_last_fallen_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_field',
            field=models.DateTimeField(),
        ),
    ]
